@host=http://localhost/api

POST {{host}}/auth/login
Content-Type: application/json

{
    "email": "swsr4wq123@gmail.com",
    "password": "123"
}

@access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMzNiZjZlMi0wNGJiLTQ5MGQtYjhjOC0xZWRjNWJkMGNjNzEiLCJnaXZlbl9uYW1lIjoiSHVuZyIsImZhbWlseV9uYW1lIjoiTmd1eWVuIiwiZW1haWwiOiJzd3NyNHdxMTIzQGdtYWlsLmNvbSIsInByZWZlcnJlZF91c2VybmFtZSI6ImNvbm11YTRuZ2FuZ3F1YSIsInJvbGUiOlsiR1VFU1QiLCJVU0VSIl0sImV4cCI6MTc3MTkyMzAyNCwiaXNzIjoiU2hvcHBlZUNsb25lIiwiYXVkIjoiU2hvcHBlZUNsb25lLVVzZXJzIn0.NMfmo_ClQ6AWCziINAfKHtEPvZddHsm_vMwlvwgQTYU
@refresh_token=CrMQpM+yYHrewm5bitmVJ3lM8QY3IvU4Rxn5sbtJ3gDWhqwEryp64azWXC/B4qhPs5V7Lbv+Vw51sbULKpMz+w==
POST {{host}}/auth/logout
Authorization: Bearer {{access_token}}
Cookie: refreshToken={{refresh_token}}


POST {{host}}/auth/register
Content-Type: application/json

{
    "email": "swsr4ws23s23sq123@gmail.com",
    "password": "123s232s",
    "firstName": "Hung",
    "lastName": "Nguyen",
    "userName": "conmua4ngangqua",
    "phoneNumber": "0123456789"
}

GET {{host}}/auth/verify
Authorization: Bearer {{access_token}}