@host=http://localhost

POST {{host}}/api/auth/register
Content-Type: application/json

{
    "email": "swsr4wq123@gmail.com",
    "password": "123",
    "firstName": "Hung",
    "lastName": "Nguyen",
    "userName": "conmua4ngangqua",
    "phoneNumber": "0123456789"
}
