@host=http://localhost/api

POST {{host}}/auth/register
Content-Type: application/json

{
    "email": "swsr4ws23s23sq123@gmail.com",
    "password": "123s232s",
    "firstName": "Hung",
    "lastName": "Nguyen",
    "userName": "conmua4ngangqua",
    "phoneNumber": "0123456789"
}
