@host=http://localhost:5287

POST {{host}}/api/auth/register
Content-Type: application/json

{
    "email": "dewded2312ed3erev@gmail.com",
    "password": "testhashed",
    "firstName": "Hung",
    "lastName": "Nguyen"
}

