@host=http://localhost/api

@access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMzNiZjZlMi0wNGJiLTQ5MGQtYjhjOC0xZWRjNWJkMGNjNzEiLCJnaXZlbl9uYW1lIjoiSHVuZyIsImZhbWlseV9uYW1lIjoiTmd1eWVuIiwiZW1haWwiOiJzd3NyNHdxMTIzQGdtYWlsLmNvbSIsInByZWZlcnJlZF91c2VybmFtZSI6ImNvbm11YTRuZ2FuZ3F1YSIsInJvbGUiOlsiR1VFU1QiLCJVU0VSIl0sImV4cCI6MTc3MTkyMzAyNCwiaXNzIjoiU2hvcHBlZUNsb25lIiwiYXVkIjoiU2hvcHBlZUNsb25lLVVzZXJzIn0.NMfmo_ClQ6AWCziINAfKHtEPvZddHsm_vMwlvwgQTYU

GET {{host}}/auth/verify
Authorization: Bearer {{access_token}}